### ISSUE TITLE
I don't know how to send data

### ISSUE THREAD

**Issue by Hengmen** [kmdreko/venator#3]
I am a beginner of Rust language and hope to learn Rust through your project. After installing Venator and launching the venator-app based on the code example in the Instructions, I noticed that no data was displayed in the venator-app. Perhaps because my knowledge of Rust is still very limited, I'm not very good at writing code to send messages. Could you please guide me on how to write and send the message correctly? Thank you very much for your help. In addition, my previous message was translated by machine. If there is anything unclear, please forgive me.
![001](https://github.com/user-attachments/assets/cf709cbb-26bf-4712-af59-5ad4144dda4c)

**Comment by kmdreko** [comment]
The Venator application works by receiving log and span data from programs using the `tracing` crate. So you'll find basic information for emitting structured logs there: https://docs.rs/tracing/0.1.40/tracing/index.html

A super basic example:

```
[dependencies]
tracing = "0.1.40"
venator = "0.2.0"
```

```
use tracing::{debug, error, info, info_span, trace, warn};
use venator::Venator;

fn main() {
    Venator::default().install();

    info_span!("a basic span").in_scope(|| {
        trace!("a trace level message");
        debug!("a debug level message");
        info!("a info level message");
        warn!("a warn level message");
        error!("a error level message");
    });
}
```

![image](https://github.com/user-attachments/assets/cd40ed3b-7147-4b23-9d9a-a4cf51079db2)

**Comment by Hengmen** [comment]
Sorry, I still can't see the log in the app interface. I noticed that communication was received through port 8362 to see if there was a communication problem. I use Wireshark to capture packets and filter with tcp.port == 8362. Found that tcp failed to connect under default conditions (capture numbers 17 and 18). I guessed it might be an environmental problem, so I modified a line of code and tested again. Judging from the packet capture data, log information can be sent (capture numbers 61 to 84), but the corresponding logs are not displayed on the app interface. I'm attaching the packet capture hope it's useful, sorry to ask for your help again.
`use tracing::{debug, error, info, info_span, trace, warn};
use venator::Venator;

fn main() {
    // Venator::default().install();
    Venator::builder().with_host("127.0.0.1:8362").build().install();

    info_span!("a basic span").in_scope(|| {
        trace!("a trace level message");
        debug!("a debug level message");
        info!("a info level message");
        warn!("a warn level message");
        error!("a error level message");
    });
}`
[venator.zip](https://github.com/user-attachments/files/17789658/venator.zip)

**Comment by kmdreko** [comment]
Ensure you are looking in the correct timeframe. The app will not automatically navigate to new events (unless the "live" button on the top right is toggled).

Either:
- `CTRL+SHIFT+G` will focus on the timeframe on the whole dataset
- Opening a new tab or re-launching the app will load to show the events
- Simply navigating by zooming and panning the graph to get to the right timeframe

**Comment by Hengmen** [comment]
Thank you very much, I have seen the data in the app.
