### ISSUE TITLE
Not able to display data like in the README.md screenshot

### ISSUE THREAD

**Issue by aitoroses** [kmdreko/venator#5]
Hello, I've been trying to display some traces and events in venator-app but I'm not sure how to use it properly and I didn't found the relevant documentation

![Captura de pantalla 2024-11-19 a las 21 15 38](https://github.com/user-attachments/assets/f03a0f91-32d4-41c2-83df-86a5a6361cf5)

![Captura de pantalla 2024-11-19 a las 21 07 44](https://github.com/user-attachments/assets/82ca744f-16ee-4a43-aa34-bd23e10e58bd)

This is the example code I'm using:

```rust
use tracing::{debug, error, info, info_span, trace, warn};
use venator::Venator;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    Venator::builder()
        .with_host("127.0.0.1:8362")
        .build()
        .install();

    let root_span = info_span!("root span");
    let _root_guard = root_span.enter();

    trace!("entering root span");

    let first_span = info_span!("first span");
    first_span.in_scope(|| {
        trace!("inside first span");
        debug!("a debug level message in first span");
        info!("an info level message in first span");

        let nested_span = info_span!("nested span");
        nested_span.in_scope(|| {
            trace!("inside nested span");
            warn!("a warn level message in nested span");
            error!("an error level message in nested span");
        });

        trace!("exiting nested span");
    });

    trace!("exiting first span");

    let second_span = info_span!("second span");
    second_span.in_scope(|| {
        trace!("inside second span");
        debug!("a debug level message in second span");
        info!("an info level message in second span");
    });

    trace!("exiting second span");

    trace!("exiting root span");

    Ok(())
}

```

Thanks!

**Comment by kmdreko** [comment]
Thanks for the report!

When trying to reproduce this I did see an issue where an existing view may not see fresh data - even when updating the timeframe. Though a number of workarounds (opening a new tab, re-launching the app, or changing the filter) should make them visible.

I'll try to fix this shortly.

**Comment by kmdreko** [comment]
I have pushed version v0.2.2 of venator-app with a fix that hopefully addresses the issue you encountered. Let me know if you're still having problems.
